export const CATEGORIES = [
  { name: "all", color: "#14b8a6" },
  { name: "technology", color: "#3b82f6" },
  { name: "science", color: "#16a34a" },
  { name: "finance", color: "#ef4444" },
  { name: "society", color: "#eab308" },
  { name: "entertainment", color: "#db2777" },
  { name: "health", color: "#14b8a6" },
  { name: "history", color: "#f97316" },
  { name: "news", color: "#8b5cf6" },
];

export const initialFacts = [
  {
    id: 1,
    text: "JavaScript was created in just 10 days by Brendan Eich in 1995.",
    source: "https://developer.mozilla.org/en-US/docs/Web/JavaScript",
    category: "technology",
    votesInteresting: 18,
    votesMindblowing: 12,
    votesFalse: 2,
    createdIn: 1995,
  },
  {
    id: 2,
    text: "Octopuses have three hearts, and their blood is blue due to a copper-based molecule called hemocyanin.",
    source: "https://ocean.si.edu/ocean-life/invertebrates/common-octopus",
    category: "science",
    votesInteresting: 25,
    votesMindblowing: 15,
    votesFalse: 1,
    createdIn: 2020,
  },
  {
    id: 3,
    text: "Mount Everest grows about 4 millimeters every year due to tectonic activity.",
    source:
      "https://www.nationalgeographic.com/adventure/article/mount-everest-facts",
    category: "geography",
    votesInteresting: 14,
    votesMindblowing: 7,
    votesFalse: 0,
    createdIn: 2018,
  },
  {
    id: 4,
    text: "Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
    source:
      "https://www.nationalgeographic.com/science/article/why-doesnt-honey-spoil",
    category: "food",
    votesInteresting: 30,
    votesMindblowing: 20,
    votesFalse: 0,
    createdIn: 2017,
  },
  {
    id: 5,
    text: "Bananas are berries, but strawberries are not.",
    source: "https://www.livescience.com/57477-why-bananas-are-berries.html",
    category: "science",
    votesInteresting: 22,
    votesMindblowing: 18,
    votesFalse: 2,
    createdIn: 2016,
  },
  {
    id: 6,
    text: "The Eiffel Tower can be 15 cm taller during the summer due to the expansion of iron in heat.",
    source: "https://www.toureiffel.paris/en/the-monument/key-figures",
    category: "engineering",
    votesInteresting: 19,
    votesMindblowing: 10,
    votesFalse: 1,
    createdIn: 2019,
  },
  {
    id: 7,
    text: "Sharks existed before trees. They have been around for more than 400 million years.",
    source: "https://www.nhm.ac.uk/discover/sharks-facts.html",
    category: "science",
    votesInteresting: 28,
    votesMindblowing: 22,
    votesFalse: 0,
    createdIn: 2021,
  },
  {
    id: 8,
    text: "A day on Venus is longer than a year on Venus due to its slow rotation.",
    source: "https://solarsystem.nasa.gov/planets/venus/overview/",
    category: "space",
    votesInteresting: 26,
    votesMindblowing: 19,
    votesFalse: 1,
    createdIn: 2022,
  },
  {
    id: 9,
    text: "Water can boil and freeze at the same time under special conditions known as the 'triple point'.",
    source:
      "https://www.scientificamerican.com/article/what-is-the-triple-point/",
    category: "science",
    votesInteresting: 21,
    votesMindblowing: 14,
    votesFalse: 0,
    createdIn: 2015,
  },
  {
    id: 10,
    text: "There are more stars in the universe than grains of sand on all the Earth's beaches combined.",
    source: "https://science.nasa.gov/astrophysics/focus-areas/how-many-stars",
    category: "space",
    votesInteresting: 33,
    votesMindblowing: 29,
    votesFalse: 1,
    createdIn: 2020,
  },
];
